### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by MattiSG** [krakenjs/swaggerize-hapi#22]
I need to enable [CORS](http://enable-cors.org) to serve my Swagger API. I don't see how I can do this with `swaggerize-hapi` at the moment.

Since this seems to me to be a fairly common use-case for a webservice library, I'd like to discuss the different implementation options before opening a PR.

I see two independent choices in the implementation.

### Activation: specific or generic

How will the user activate CORS in `swaggerize-hapi`? I see two options:

1. Add a generic “pass this to Hapi” config option. Less obvious for what is probably a common use-case, but more future-proof and possibly solving other issues that may arise. This options object would be merged with the generated route definition, probably [here](https://github.com/krakenjs/swaggerize-hapi/blob/f0c12aadfc6c46115f9e2a6122bbe2fe1573356c/lib/index.js#L96-L101).
2. Add a “cors” config option that is manually added to the route definition. Easier to document.

### Default value

1. `true`: enable CORS by default for Swagger routes, considering this is a webservice library.
2. `false`: let the user opt-in. Keeps current behaviour, but means the user has to understand why the thing he made does not work, and to learn about CORS.

- - - 

I'm in favour of generic + default to `true`, as that's the combination that puts the less burden on both user and maintainer.

**Comment by tlivings** [comment]
Fixed in `swaggerize-hapi@1.0.0-rc.3`
