### ISSUE TITLE
Authentication interface missing

### ISSUE THREAD

**Issue by peteyy** [krakenjs/swaggerize-hapi#31]
I was trying to implement Hapi jwt authentication into my existing swagger project and I haven't found any official way in the docs.

In each route generated, I had to add these few lines to every route

```
    auth: 'token',
    plugins: {
      hapiAuthorization: {
        roles: route.authorization
      }
    }
```

It would be so much better to provide an interface to customize the route generation! :+1:
I'm quite new to these things, if there is any way I can help, tell me. :)

**Comment by tlivings** [comment]
Thanks for brining it up - it's on its way, just haven't finished yet!

**Comment by tlivings** [comment]
This is almost done for `swaggerize-express`. Hapi is up next.

**Comment by appedemic** [comment]
It seems that swaggerize-hapi is using swaggerize-routes which has support for "x-authorize", but how do I use it. I can get swaggerize-hapi to include a file through the "x-authorize" field but I'm missing how I can add a functional authorization method to the system.

**Comment by tlivings** [comment]
Hapi authorization interface requires a bit more wiring to get right. It's a lot easier with express. I haven't completed this work, even though it using the newer swaggerize-routes.
