### ISSUE TITLE
Validate responses against swagger definition

### ISSUE THREAD

**Issue by brainsiq** [krakenjs/swaggerize-hapi#35]
It'd be really nice if there was a way to validate the API responses against the swagger.json file to ensure that the handlers are returning the documented responses. I guess Hapi's onPreResponse extension point might be the right place to do this.

Something to consider if implementing this is that it could be undesirable for apps or endpoints where high performance is required. In this case there could be an option to disable the check completely, or do something like run the check asynchronously and just log the result for reporting.

**Comment by tlivings** [comment]
The reason it doesn't is because an error in server implementation should never be returned to a user, whereas an error in user input should.

The purpose of the generated tests are to cover response validation.

**Comment by tlivings** [comment]
And when I say "never" I really mean "should be avoided".

**Comment by brainsiq** [comment]
Point taken. I hadn't seen these tests as I didn't use the generator. Will have to take a look at that.

Cheers.
