### ISSUE TITLE
JWT authentication support

### ISSUE THREAD

**Issue by Kitanotori** [krakenjs/swaggerize-hapi#46]
How do I set up JWT authentication and authorization in swaggerize-hapi (using e.g. [hapi-auth-jwt2](https://github.com/dwyl/hapi-auth-jwt2))? Does Swagger definition file provide a way to configure authentication and authorization per-route basis?

**Comment by tlivings** [comment]
Sorry I didn't get back on this sooner. I am working on improving auth scheme support.

**Comment by fedirch** [comment]
would be good to have it.

**Comment by Kitanotori** [comment]
I hope you guys could solve this together (https://github.com/dwyl/hapi-auth-jwt2/issues/154). Having support for JWT authentication - as Swagger doesn't seem to provide it by default - would be awesome.

**Comment by Bazze** [comment]
I'm not sure, but I played around a bit today and to me it seems that it's fully possible to this already. I followed the documentation linked below and got it working!

https://github.com/krakenjs/swaggerize-hapi#authentication
https://github.com/dwyl/hapi-auth-jwt2#example

Add `securityDefinitions` in your swagger file and annotate the paths you want to protect with the `security` attribute:
```javascript
{
  "securityDefinitions": {
    "jwt": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "paths": {
    "/pets": {
      "get": {
        "security": [
          {
            "jwt": []
          }
        ],
        "summary": "List all pets",
        "operationId": "listPets",
        "tags": [
          "pets"
        ],
        [...]
      }
    }
  }
}
```

Then you need to register the auth scheme _before_ you register the swaggerize plugin. Your `server.js` should look something like this:
```javascript
'use strict';

var Hapi = require('hapi');
var Swaggerize = require('swaggerize-hapi');
var Path = require('path');
var JwtAuthScheme = require('hapi-auth-jwt2');

var Server = new Hapi.Server();

Server.connection({ port: 8000 });

Server.register(JwtAuthScheme, () => {
    Server.auth.strategy('jwt', 'jwt', {
        key: 'secret-key-here',
        verifyOptions: {
            tokenType: 'Bearer',
            algorithms: [ 'HS256' ]
        },
        validateFunc: function (decoded, request, callback) {
            var people = { // our "users database"
                1: {
                    id: 1,
                    name: 'Jen Jones'
                }
            };

            // do your checks to see if the person is valid
            if (!people[decoded.uid]) {
                return callback(null, false);
            } else {
                return callback(null, true);
            }
        }
    });

    Server.register({
        register: Swaggerize,
        options: {
            api: Path.resolve('./config/swagger.json'),
            handlers: Path.resolve('./handlers')
        }
    }, function () {
        Server.start(function () {
            Server.plugins.swagger.setHost(Server.info.host + ':' + Server.info.port);
            /* eslint-disable no-console */
            console.log('App running on %s:%d', Server.info.host, Server.info.port);
            /* eslint-disable no-console */
        });
    });
});
```

However, when using the `securityDefinitions` the generator creates a `security` folder with a file which seems to be a middleware that should be called for authorizing the request but It never seems to get triggered (only the `validateFunc` function provided to the auth strategy is triggered). Generated tests won't work either until you load the auth scheme correctly in there as well.

**Comment by Kitanotori** [comment]
@Bazze It is's necessary to be able to define also authorization scopes.

**Comment by aguerere** [comment]
@Kitanotori @Bazze do you guys have any updates on the authorization scopes? This would be awesome to have!

**Comment by Bazze** [comment]
No unfortuantely not @aguerere. I actually decided to switch approach and now using the [glennjones/hapi-swagger](https://github.com/glennjones/hapi-swagger) lib instead, generating the Swagger doc from my route definitions.

**Comment by tlivings** [comment]
The latest supports far more flexible configuration. Closing this now.
