### ISSUE TITLE
Adding a header parameter disallows other unspecified headers

### ISSUE THREAD

**Issue by sommestad** [krakenjs/swaggerize-hapi#50]
Added a _header_ parameter to one of the paths defined in our API spec:

``` json
{
  "name": "accept-language",
  "in": "header",
  "type": "string",
  "description": "Preferred language of the user",
  "enum": [
    "en",
    "sv"
  ]
}
```

When doing so, the validation from swaggerize-hapi automatically disallows the use of _any_ other headers. I.e. if the client provides an `Accept` or `Connection` header, the entire request will fail validation and just return an error to the client.

Is this by design? Should the underlying validation schema take care of this somehow?

---

Also: Thanks for an awesome library. 👏

**Comment by subeeshcbabu** [comment]
The `Joi` validation object created for `headers` seems to restricting unspecified headers. I think we need to add `allowUnknown: true` option to the `Joi` schema object that gets created, so that, it will allow unspecified headers and validate only the headers defined by api/schema.

**Comment by tlivings** [comment]
Published this morning.
