### ISSUE TITLE
Get rid of trailing slashes in routes

### ISSUE THREAD

**Issue by Kitanotori** [krakenjs/swaggerize-hapi#51]
It seems that currently the API docs are always served from a path with trailing slash. For example, if I have a basepath '/api', and I want API docs to be shown at the basepath (i.e. docspath: '/'), I can access API docs only from '/api/', but not from '/api'. I think this is a bug that needs fixing. I recommend adding a path normalization function; for example like this: https://github.com/Kitanotori/swaggerize-routes/commit/be0fbb4ce0185ba6e37d30126ab6ee01c00da30f, which can then be used like this: https://github.com/Kitanotori/swaggerize-hapi/commit/9e1f97d94ba324f620221080ac70775b4c6ffdd1.

The industry seems to be moving towards no-trailing-slash URLs, so I think it is appropriate to make sure that no generated routes (except of course '/') have trailing slash. Because **a URI with a trailing slash does not denote the same resource** as an URI without a trailing slash, allowing developers to mix these two schemes creates unnecessary confusion and adds complexity. Therefore, I propose that swaggerize-hapi enforces a policy of no-trailing-slash in routes.

**Comment by tlivings** [comment]
Published this morning.
