### ISSUE TITLE
How to enable caching?

### ISSUE THREAD

**Issue by vitorbaptista** [krakenjs/swaggerize-hapi#55]
I read the code but couldn't find a functionality for this (maybe it doesn't exist?). I'd like to set the `Cache-Control` header using hapijs. For example:

``` javascript
server.route({
    path: '/user/{id}',
    config: {
        cache: {
            expiresIn: 30 * 1000,
            privacy: 'private'
        }
    },
    // ...
});
```

Is there a way to customize that `config.cache` element in the created routes?

**Comment by subeeshcbabu** [comment]
`cache` is not an option that is supported right now as per - https://github.com/krakenjs/swaggerize-hapi#configuration-options. A `cache` option applicable to all the routes can be easily implemented, like this - https://github.com/krakenjs/swaggerize-hapi/blob/master/lib/index.js#L54 (`options.cors`).

However if the cache config needs to be based on routes (need to be added to the generated route configs), then the support for that seems like not that straightforward. May be the config in general need to support, route based options? Say the swagger api can define `^x-config` for a `path`/`route` and this `config` handler can be applied to corresponding routes, just thoughts.

**Comment by vitorbaptista** [comment]
Adding `options.cache` would certainly be useful (and is a nice low-hanging fruit), but unfortunately not enough for me :/

Volos.js solves this issue with a similar approach as you suggested, adding a custom `x-a127-services` to configure things like caching, authorization, etc. (see https://github.com/apigee-127/a127-documentation/wiki/Quick-Start:-Add-Caching). I have mixed feelings about this, because it feels a bit like abusing Swagger. I think caching details are unrelated to an API specification, but maybe it's the cleanest way it could be done.

**Comment by tlivings** [comment]
Done as of 4.0.0.
