### ISSUE TITLE
security schemes support for other than apiKey

### ISSUE THREAD

**Issue by subeeshcbabu** [krakenjs/swaggerize-hapi#56]
Looks like the only security scheme that, this module supports, is the `apiKey` type. Any in-progress plans/efforts to extend support for other scheme types?

Also the assert error message here - https://github.com/krakenjs/swaggerize-hapi/blob/master/lib/index.js#L127 
`None api_key security schemes not supported.` is confusing. Should this be changed to something like  `Security schemes other than api_key are not supported`?

**Comment by fedirch** [comment]
+1

**Comment by jishi** [comment]
At least basic auth actually works if one remove that assertion, so maybe consider adding that as a non exception perhaps?

**Comment by leachiM2k** [comment]
Generally +1

How can we put progress in this issue?

**Comment by tlivings** [comment]
@leachiM2k  contributions welcome. 

I have started to revisit this recently and have some ideas. It's not as straight forward in Hapi due to the way authentication works, but I think I have an ok approach in mind.

**Comment by jdarling** [comment]
Seems to me that there should be an option that would disable that error or remove it completely.  Custom auth works just fine and enforcing it this way just means that we have to fork the repo, comment out the line, and install from our custom version.  Generally a PITA.

**Comment by tlivings** [comment]
Latest has much more flexible configuration for security.
