### ISSUE TITLE
How do I add route tags to generated routes?

### ISSUE THREAD

**Issue by vimcat** [krakenjs/swaggerize-hapi#70]
How do I add route tags to the generated routes? I'm trying to use a generator to create the swagger doc that requires tags on the routes. My json file has tags specified for each path but it doesn't seem to get translated into the handlers. If this isn't the way to create the swagger doc that goes with the generated endpoints, how is it supposed to work with this generator?

**Comment by tlivings** [comment]
Sorry for the long wait. 

Since this module builds routes dynamically there is no way to explicitly specify them. 

However, the latest version automatically tags the routes with the operationId.
