### ISSUE TITLE
Bump up version

### ISSUE THREAD

**Issue by skawaguchi** [krakenjs/swaggerize-hapi#71]
@tlivings would it be possible to bump up the version to account for [this commit](https://github.com/krakenjs/swaggerize-hapi/commit/b42dde37ff598b189408e7f8716ce8655169a749)? Anyone using Yarn, Node 5+, and swaggerize-hapi gets an error.

**Comment by subeeshcbabu** [comment]
@tlivings Can you add me as a maintainer.

**Comment by tlivings** [comment]
Sorry, I've bumped as of this morning.
