### ISSUE TITLE
A single item in a collection results in an error.

### ISSUE THREAD

**Issue by rodoabad** [krakenjs/swaggerize-hapi#72]
"must be an array"

![capture](https://cloud.githubusercontent.com/assets/1240667/23187847/00347604-f852-11e6-971b-76584ea7ee2f.JPG)

So...

` 'http://localhost:8000/api/part-returns?d=1&d=2'` will pass. But ` 'http://localhost:8000/api/part-returns?d=1` will fail.

**Comment by rodoabad** [comment]
Found a related issue perhaps? https://github.com/krakenjs/swaggerize-hapi/issues/63

**Comment by tlivings** [comment]
I don't think it is related. Will dig into this shortly. Starting to perform a major update that will address several issues.

**Comment by tlivings** [comment]
Fixed.
