### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by YvesPasteur** [krakenjs/swaggerize-hapi#75]
Hi,

The last available version (2.0.1) doesn't include the commit (https://github.com/krakenjs/swaggerize-hapi/commit/6ca934fbb569fab8d8961c93524050c0de8b01ad).
Could you create a new version ?

Thanks !

**Comment by kangchals** [comment]
+1
Me too!!!!!
And Can anyone explain me why it happens?
The package.json on this repoi tells that the version is 2.0.1.
However, the result of code in my directory using npm install swaggerize-hapi@latest --save
also said the version is 2.0.1 but the last commit is not included...
Is there any other steps to include the commit? Thanks!

**Comment by tlivings** [comment]
should be addressed. also new version!
