### ISSUE TITLE
null type in json schema

### ISSUE THREAD

**Issue by stickyhands** [krakenjs/swaggerize-hapi#77]
type null in json schema throw an exception while its a valid type

> Could not resolve type: null.

**Comment by Pryscy** [comment]
+1

**Comment by tlivings** [comment]
Can you provide an example? `null` is not an acceptable type in swagger 2.0 that I know of.

**Comment by tlivings** [comment]
Closing unless a good example comes up.

**Comment by stickyhands** [comment]
If im not mistaken, that json schema looks valid to me:

```json
{
    "id": "https://api.xxx.com/v3/schemas/category_create",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "parent_category_id": {
            "type": ["string", "null"],
            "format": "uuid"
        },
        "reference": {
            "type": "string",
            "minLength": 1
        },
        "priority": {
            "type": "integer",
            "minimum": 0
        }
    },
    "required": [
        "parent_category_id",
        "reference",
        "priority"
    ]
}
```

unfortunately I got an error when the app is booting : 

> AssertionError: Could not resolve type: string,null.
> at resolvetype (/srv/www/api.xxx.com/node_modules/enjoi/lib/enjoi.js:103:16)
> at resolve (/srv/www/api.xxx.com/node_modules/enjoi/lib/enjoi.js:23:20)
> at /srv/www/api.xxx.com/node_modules/enjoi/lib/enjoi.js:144:25
> at Array.forEach (native)
> at resolveproperties (/srv/www/api.xxx.com/node_modules/enjoi/lib/enjoi.js:139:41)
> at object (/srv/www/api.xxx.com/node_modules/enjoi/lib/enjoi.js:157:36)
> at resolvetype (/srv/www/api.xxx.com/node_modules/enjoi/lib/enjoi.js:92:29)
> at resolve (/srv/www/api.xxx.com/node_modules/enjoi/lib/enjoi.js:23:20)
> at enjoi (/srv/www/api.xxx.com/node_modules/enjoi/lib/enjoi.js:251:12)
> at Object.make (/srv/www/api.xxx.com/node_modules/swaggerize-routes/lib/validator.js:98:26)

**Comment by tlivings** [comment]
What I meant was, according to the supported types in the swagger specification, null is not a type.
