### ISSUE TITLE
Add route identifier to generated routes

### ISSUE THREAD

**Issue by alexb-uk** [krakenjs/swaggerize-hapi#84]
I have a need to retrieve a generated route from the HAPI server and the suggested solution was to use Server.lookup(). However this doesn't work as swaggerize-hapi doesn't give the generated routes an id.

See HAPI doc's: https://github.com/hapijs/hapi/blob/master/API.md#server.lookup()

My suggestion is to define the routes using some agreed format, e.g.:

> get-/resources
> get-/resources/{id}
> post-/resources

This could easily be added with the following code:
**node_modules/swaggerize-hapi/lib/index.js:** line: 52
```javascript
config = {
	pre: [],
	handler: undefined,
	cors: options.cors,
	id: `${route.method}-${route.path}`
};
```

Thoughts?

Am happy to create a PR with some tests if people think this is a good approach.

**Comment by tlivings** [comment]
This is done in the latest. Using the operationId from the swagger document.
